---
archived: ~
categories: ~
keywords: ~
published: ~
status: skiss
title: Tabelldata för rutnät för funktionsjämförelse
---


- Feature: "[à la carte AI](https://iconoclasts.blog/joe/wikis#the-la-carte-approach)"
  Orion: "&check;"
- Feature: "SSO: Kerberos / Aktiv katalog / OpenID Integrering"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "Endast SCIM"
  Confluence: "&check;"
- Feature: "FIPS 140-3 kompatibel infrastruktur med nolltillit"
  Orion: "&check;"
- Feature: "HIPPA-kompatibel"
  Orion: "&check;"
- Feature: "FedRAMP Infrastruktur"
  Orion: "Serverinstallation"
- Feature: "Global faktadata"
  Orion: "&check;"

- Feature: "Arbetsflöde i webbläsare (mobilvänligt)"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "&check;"
  Confluence: "&check;"
- Feature: "DAV-stöd"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Inkrementella byggen"
  Orion: "&check;"
- Feature: "Obegränsade kontorsbyggnader"
  Orion: "&check;"

- Feature: "Schemalagda byggen av endast dynamiskt innehåll"
  Orion: "&check;"
- Feature: "Stöd för 3:e partanalys"
  Orion: "&check;"
- Feature: "Enhetsmeddelanden för bevakningslista"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Flerspråkig (i18n)"
  Orion: "&check;"
  Notion: "&check;"
- Feature: 'Helt sökbar/utbytbar <span class="editormd-tex">\KaTeX</span>/PCRE-uttryck'
  Orion: "&check;"
  Confluence: "$$$"
- Feature: "Samordnad"
  Orion: "&check;"
  Confluence: "[Nej](https://jira.atlassian.com/browse/CONFSERVER-26528)"

- Feature: "Stöd för vit etikett"
  Orion: "&check;"
- Feature: "Installerbar intern företags-VPN"
  Orion: "Serverinstallation"
- Feature: "Fungerar nedkopplad"
  Orion: "&check;"
  Notion: "&check;"
- Feature: "Lätt 3:e part 'Hämtningsbegäran' Arbetsflöde för medverkande"
  Orion: "&check;"
- Feature: "[GitHub-integrering](https://youtu.be/FRc4qZkxVaI) med IDE &amp; Stöd för åtgärder"
  Orion: "&check;"
- Feature: "Obegränsade förhandsvisningar"
  Orion: "&check;"
  Slab: "&check;"
  Notion: "&check;"
  Confluence: "&check;"

- Feature: "Obegränsade platser"
  Orion: "Företag &amp; Serverinstallation"
- Feature: "Obegränsad versionskontrollhistorik"
  Orion: "&check;"
- Feature: "Integrerad spårning av URL-ändring"
  Orion: "&check;"
- Feature: "Hem - Kundavdelning"
  Orion: "&check;"
- Feature: "[3D Vektorgrafik](features#h2-interactive-mathematical-vector-graphics-with-vectorgraphics-asymptote) Integrering"
  Orion: "&check;"
- Feature: "Stöd för SSI/CGI/mod_perl/mod_wasm"
  Orion: "&check;"
- Feature: "Detaljerad datalager-/.htaccess synkroniserade åtkomstkontrollistor"
  Orion: "&check;"
- Feature: "300 Mbyte/s fullständiga webbplatsbyggen"
  Orion: "&check;"
- Feature: "16-256-vägs samtidiga byggen"
  Orion: "&check;"
- Feature: "Total ägandekostnad &lt; 10000 USD/år för företag"
  Orion: "&check;"
- Feature: "Omfattande servicenivåavtal på 99,99 %"
  Orion: "Företag &amp; Serverinstallation"
- Feature: "Sökbar dokumentstatus"
  Orion: "&check;"
  Slab: "&check;"
- Feature: 'Nedsättning <span class="editormd-tex">\leftrightarrow \LaTeX</span> Automatisering'
  Orion: "&check;"
- Feature: "Automatisk översättning av AI NLP"
  Orion: "&check;"