---
categories: ~
keywords: ~
status: черновик
title: Данные таблицы для сетки сравнения характеристик
---


- Feature: "[à la carte (BYOAI)AI](https://iconoclasts.blog/joe/wikis#the-à-la-carte-approach17)"
  Orion: "&check;"
- Feature: "SSO: Kerberos / Активный каталог / Интеграция OpenID"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "Только SCIM"
  Confluence: "&check;"
- Feature: "Инфраструктура с нулевым доверием, соответствующая требованиям FIPS 140-3"
  Orion: "&check;"
- Feature: "Соответствует HIPPA"
  Orion: "&check;"
- Feature: "Инфраструктура FedRAMP"
  Orion: "Установка сервера"
- Feature: "Глобальная база данных фактов"
  Orion: "&check;"
- Feature: "<span class='badge bg-success'>Новый</span> Проверка внутренней/внешней ссылки"
  Orion: "&check;"

- Feature: "Поток операций в браузере (для мобильных устройств)"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "&check;"
  Confluence: "&check;"
- Feature: "Поддержка DAV"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Поэтапные сборки"
  Orion: "&check;"
- Feature: "Неограниченное число построений ветвей"
  Orion: "&check;"
- Feature: "Пользовательский провайдер OpenID"
  Orion: "Предприятие &amp; Установка сервера"
- Feature: "Только запланированные сборки динамического контента"
  Orion: "&check;"
- Feature: "Поддержка аналитики 3-й стороны"
  Orion: "&check;"
- Feature: "Уведомления устройства контрольного списка"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Многоязычный (i18n)"
  Orion: "&check;"
  Notion: "&check;"
- Feature: "Полностью поиск/замена <span class='editormd-tex'>\\KaTeX</span>Выражения /PCRE/Lucene"
  Orion: "&check;"
- Feature: "Федеративный"
  Orion: "&check;"
  Confluence: "[Нет](https://jira.atlassian.com/browse/CONFSERVER-26528)"

- Feature: "Поддержка White Label"
  Orion: "&check;"
- Feature: "Установка внутри корпоративного VPN"
  Orion: "Установка сервера"
- Feature: "Работает автономно"
  Orion: "&check;"
  Notion: "&check;"
- Feature: "Простой поток операций соавтора 3-й стороны Pull-Request"
  Orion: "&check;"
- Feature: "[GitHub Интеграция](https://youtu.be/FRc4qZkxVaI) с/ IDE &amp; Поддержка действий"
  Orion: "&check;"
- Feature: "Безлимитный просмотр"
  Orion: "&check;"
  Slab: "&check;"
  Notion: "&check;"
  Confluence: "&check;"

- Feature: "Неограниченное количество мест"
  Orion: "Предприятие &amp; Установка сервера"
- Feature: "Без ограничений, Согласованная история контроля версий"
  Orion: "&check;"
- Feature: "Интегрированное отслеживание изменений URL-адресов"
  Orion: "&check;"
- Feature: "Хостинг сайта"
  Orion: "&check;"
- Feature: "[3D Векторная графика](features#h2-interactive-mathematical-vector-graphics-with-vectorgraphics-asymptote) Интеграция"
  Orion: "&check;"
- Feature: "Поддержка SSI / CGI / mod_perl / mod_wasm"
  Orion: "&check;"
- Feature: "Точные списки управления доступом для репозитория/синхронизированные списки управления доступом.htaccess"
  Orion: "&check;"
- Feature: "Полная сборка сайта 300 МБ/с"
  Orion: "&check;"
- Feature: "16-256 параллельные сборки"
  Orion: "&check;"
- Feature: "Общая стоимость владения &lt; $25000/год для предприятия"
  Orion: "&check;"
- Feature: "Комплексное соглашение об уровне обслуживания (SLA) 99,99%"
  Orion: "Предприятие &amp; Установка сервера"
- Feature: "Статус документа с возможностью поиска"
  Orion: "&check;"
  Slab: "&check;"
- Feature: "Снижение цен <span class='editormd-tex'>\\leftrightarrow \\LaTeX</span> [Автоматизация](https://www.youtube.com/watch?v=4JxfXTBe4g8)"
  Orion: "&check;"
- Feature: "ИИ: автоматический перевод NLP"
  Orion: "&check;"