---
archived: ~
categories: ~
keywords: ~
published: ~
status: skiss
title: Tabelldata för rutnät för funktionsjämförelse
---


- Feature: "SSO: Kerberos / Aktiv katalog / OpenID Integration"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "Endast SCIM"
  Confluence: "&check;"
- Feature: FIPS 140-3-kompatibel Zero Trust-infrastruktur
  Orion: "&check;"
- Feature: "FedRAMP Infrastruktur"
  Orion: "Serverinstallation"
- Feature: "Webbläsararbetsflöde (mobilvänligt)"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "&check;"
  Confluence: "&check;"
- Feature: "DAV-support"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Inkrementella byggen"
  Orion: "&check;"
- Feature: "Obegränsade kontorsbyggen"
  Orion: "&check;"
- Feature: "Endast schemalagda byggen av dynamiskt innehåll"
  Orion: "&check;"
- Feature: "3:e partens analyssupport"
  Orion: "&check;"
- Feature: "Titta på listan Enhetsmeddelanden"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Multilingual (i18n)"
  Orion: "&check;"
- Feature: 'Helt sökbar <span class="editormd-tex">\KaTeX</span> Uttryck'
  Orion: "&check;"
  Confluence: "$$$"
- Feature: "Samordnade"
  Orion: "&check;"
  Confluence: "[Nej](https://jira.atlassian.com/browse/CONFSERVER-26528)"
- Feature: "Stöd för vit etikett"
  Orion: "&check;"
- Feature: "Installerbar inuti företags-VPN"
  Orion: "Serverinstallation"
- Feature: "Fungerar nedkopplad"
  Orion: "&check;"
- Feature: 'Enkelt 3:e parts bidragsarbetsflöde för begäran'
  Orion: "&check;"
- Feature: "[GitHub Integrering](https://youtu.be/FRc4qZkxVaI) med integrerad utvecklingsmiljö &amp; Stöd för åtgärder"
  Orion: "&check;"
- Feature: "Obegränsade förhandsvisningar"
  Orion: "&check;"
  Slab: "&check;"
  Notion: "&check;"
  Confluence: "&check;"
- Feature: "Obegränsade platser"
  Orion: Företag &amp; Serverinstallation"
- Feature: "Obegränsad versionskontrollhistorik"
  Orion: "&check;"
- Feature: "Integrerad spårning av URL-ändring"
  Orion: "&check;"
- Feature: "Webbplatshotell"
  Orion: "&check;"
- Feature: "[3D-vektorgrafik](features#h2-interactive-mathematical-vector-graphics-with-vectorgraphics-asymptote) Integrering"
  Orion: "&check;"
- Feature: "SSI / CGI / mod_perl / mod_wasm support"
  Orion: "&check;"
- Feature: "Befintlig åtkomstkontrollista för källager"
  Orion: "&check;"
- Feature: "500 Mbyte/s fullständiga webbplatsbyggen"
  Orion: "&check;"
- Feature: "8-64-vägs samtidiga byggen"
  Orion: "&check;"
- Feature: TCO &lt; $6000/år för Enterprise"
  Orion: "&check;"
- Feature: "Omfattande 99,99 % SLA"
  Orion: Företag &amp; Serverinstallation"
- Feature: "Status på sökbart dokument"
  Orion: "&check;"
  Slab: "&check;"
- Feature: 'Nedsättning <span class="editormd-tex">\leftrightarrow \LaTeX</span> Automatisering
  Orion: "&check;"
- Feature: Automatisk översättning av AI NLP
  Orion: "&check;"
