---
categories: borrador
keywords: ~
status: ~
title: Datos de tabla para cuadrícula de comparación de funciones
---


- Feature: "SSO: Kerberos / Directorio activo / Integración OpenID"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "Solo SCIM"
  Confluence: "&check;"
- Feature: "Infraestructura de confianza cero compatible con FIPS 140-3"
  Orion: "&check;"
- Feature: "FedRAMP Infraestructura"
  Orion: "Instalación de servidor"
- Feature: "Flujo de trabajo en el navegador (amigable para dispositivos móviles)"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "&check;"
  Confluence: "&check;"
- Feature: "Soporte de DAV"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Creación incremental"
  Orion: "&check;"
- Feature: "Creación ilimitada de sucursales"
  Orion: "&check;"
- Feature: "Creación programada solo de contenido dinámico"
  Orion: "&check;"
- Feature: "Soporte de análisis de 3a parte"
  Orion: "&check;"
- Feature: "Ver notificaciones de dispositivos de lista"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Multilingüe"
  Orion: "&check;"
- Feature: 'Expresiones <span class="editormd-tex">\KaTeX</span> totalmente aptas para búsqueda'
  Orion: "&check;"
  Confluence: "$$$"
- Feature: "Federado"
  Orion: "&check;"
  Confluence: [NO](https://jira.atlassian.com/browse/CONFSERVER-26528)"
- Feature: "Soporte de etiqueta blanca"
  Orion: "&check;"
- Feature: "Instalable dentro de VPN corporativa"
  Orion: "Instalación de servidor"
- Feature: "Funciona sin conexión"
  Orion: "&check;"
- Feature: 'Fácil flujo de trabajo de colaborador de 3a parte con solicitud de extracción'
  Orion: "&check;"
- Feature: "[GitHub Integration](https://youtu.be/FRc4qZkxVaI) con soporte de IDE y acciones"
  Orion: "&check;"
- Feature: "Vistas previas ilimitadas"
  Orion: "&check;"
  Slab: "&check;"
  Notion: "&check;"
  Confluence: "&check;"
- Feature: "Asientos ilimitados"
  Orion: "Instalación de Enterprise &amp; Server"
- Feature: "Historial ilimitado de control de versiones"
  Orion: "&check;"
- Feature: "Seguimiento integrado de cambios de URL"
  Orion: "&check;"
- Feature: "Alojamiento de sitios web"
  Orion: "&check;"
- Feature: [Gráficos vectoriales 3D](features#h2-interactive-mathematical-vector-graphics-with-vectorgraphics-asymptote) Integración"
  Orion: "&check;"
- Feature: "Soporte de SSI / CGI / mod_perl / mod_wasm"
  Orion: "&check;"
- Feature: "ACL detallada en repositorio de origen"
  Orion: "&check;"
- Feature: "Construcciones de Sitios Completos de 500 MB/s"
  Orion: "&check;"
- Feature: "Construcciones simultáneas de 8-64 vías"
  Orion: "&check;"
- Feature: "TCO < $6000/año para Enterprise"
  Orion: "&check;"
- Feature: "SLA integral del 99,99%"
  Orion: "Instalación de Enterprise &amp; Server"
- Feature: "Estado de documento apto para búsqueda"
  Orion: "&check;"
  Slab: "&check;"
- Feature: 'Automatización de <span class="editormd-tex">\leftrightarrow \LaTeX</span>'
  Orion: 