---
categories: ~
keywords: ~
status: borrador
title: Datos de tabla para cuadrícula de comparación de funciones
---


- Feature: "[A la carta (BYOAI)AI](https://iconoclasts.blog/joe/wikis#the-la-carte-approach)"
  Orion: "&check;"
- Feature: "SSO: Integración de Kerberos/Directorio activo/OpenID"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "Solo SCIM"
  Confluence: "&check;"
- Feature: "Infraestructura Cero Confianza Cifrada Post-Quantum compatible con FIPS 140-3"
  Orion: "&check;"
- Feature: "Conformidad con HIPPA"
  Orion: "&check;"
- Feature: "Infraestructura FedRAMP"
  Orion: "Instalación del servidor"
- Feature: "Base de datos de hechos globales"
  Orion: "&check;"

- Feature: "Flujo de trabajo dentro del navegador (amigable para dispositivos móviles)"
  Orion: "&check;"
  Slab: "&check;"
  Notify: "&check;"
  Confluence: "&check;"
- Feature: "Soporte de DAV"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Compilaciones incrementales"
  Orion: "&check;"
- Feature: "Construcciones de sucursales ilimitadas"
  Orion: "&check;"
- Feature: "Proveedor OpenID personalizado"
  Orion: "Empresa &amp; Instalación del servidor"
- Feature: "Solo compilaciones programadas de contenido dinámico"
  Orion: "&check;"
- Feature: "Soporte de análisis de 3ª parte"
  Orion: "&check;"
- Feature: "Notificaciones de dispositivo de lista de comprobaciones"
  Orion: "&check;"
  Confluence: "&check;"
- Feature: "Multilingüe (i18n)"
  Orion: "&check;"
  Notion: "&check;"
- Feature: 'Se puede buscar/sustituir completamente <span class="editormd-tex">\KaTeX</span>Expresiones /PCRE"
  Orion: "&check;"
- Feature: "Federado"
  Orion: "&check;"
  Confluence: "[NO](https://jira.atlassian.com/browse/CONFSERVER-26528)"

- Feature: "Compatibilidad con marca blanca"
  Orion: "&check;"
- Feature: "Instalable dentro de VPN corporativa"
  Orion: "Instalación del servidor"
- Feature: "Funciona sin conexión"
  Orion: "&check;"
  Notion: "&check;"
- Feature: "Flujo de trabajo de colaborador de "solicitud de extracción" de 3ª parte sencilla"
  Orion: "&check;"
- Feature: "[GitHub Integración](https://youtu.be/FRc4qZkxVaI) con IDE &amp; Soporte de acciones"
  Orion: "&check;"
- Feature: "Vista previa ilimitada"
  Orion: "&check;"
  Slab: "&check;"
  Notion: "&check;"
  Confluence: "&check;"

- Feature: "Asientos ilimitados"
  Orion: "Empresa &amp; Instalación del servidor"
- Feature: "Historial de control de versiones ilimitado"
  Orion: "&check;"
- Feature: "Seguimiento integrado de cambios de URL"
  Orion: "&check;"
- Feature: "Alojamiento web"
  Orion: "&check;"
- Feature: "[3D Gráficos vectoriales](features#h2-interactive-mathematical-vector-graphics-with-vectorgraphics-asymptote) Integración"
  Orion: "&check;"
- Feature: "SSI / CGI / mod_perl / mod_wasm soporte"
  Orion: "&check;"
- Feature: "ACL sincronizadas de repositorio/.htaccess detallado"
  Orion: "&check;"
- Feature: "Compilaciones completas del sitio de 300 MB/s"
  Orion: "&check;"
- Feature: "Compilaciones Simultáneas de 16-256 Direcciones"
  Orion: "&check;"
- Feature: "Costo total &lt; $10000/año para empresas"
  Orion: "&check;"
- Feature: "SLA integral del 99,99 %"
  Orion: "Empresa &amp; Instalación del servidor"
- Feature: "Estado de documento apto para búsqueda"
  Orion: "&check;"
  Slab: "&check;"
- Feature: 'Rebaja <span class="editormd-tex">\leftrightarrow \LaTeX</span> Automatización'
  Orion: "&check;"
- Feature: "Traducción automática de NLP de IA"
  Orion: "&check;"